name: Publish Wiki
on:
  push:
    branches: [ main ]
    paths: [ 'docs/wiki/**' ]
  workflow_dispatch: {}

permissions:
  contents: write

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Checkout wiki repo
        uses: actions/checkout@v4
        with:
          repository: ${{ github.repository }}.wiki
          path: wiki
      - name: Sync wiki content
        run: |
          rsync -a --delete docs/wiki/ wiki/
          cd wiki
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add -A
          if git diff --cached --quiet; then
            echo "No changes to publish"
          else
            git commit -m "Update wiki from docs/wiki on $GITHUB_SHA"
            git push
          fi